# Generated by Django 3.1.3 on 2020-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=50)),
                ('growth_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
