# Generated by Django 3.1.3 on 2020-11-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StructuredFinancialInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SFI_id', models.IntegerField(default=0)),
                ('Knock_in', models.IntegerField(default=0)),
                ('Knock_out', models.IntegerField(default=0)),
                ('put_strike', models.IntegerField(default=0)),
                ('fp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialproduct', verbose_name='the financial product id')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stockinfo', verbose_name='the stock id')),
            ],
        ),
    ]
