# Generated by Django 3.1.3 on 2020-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_financialproduct_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='growth_rate',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='price',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
    ]
