# Generated by Django 3.1.2 on 2020-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201126_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='date',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='structuredfinancialinvestment',
            name='Knock_in',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='structuredfinancialinvestment',
            name='Knock_out',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='structuredfinancialinvestment',
            name='put_strike',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
    ]
